 investmentForm:{
                    _token : csrf,
                    deal_id: "{{$deal->id}}",
                    investor_id:'',
                    investor_profile_id:'',
                    deal_class_id:'',
                    offering_id:'',
                    investment_amount:'',
                    pcb_ownership:'',
                    op_ownership:'',
                    pcb_distribution:'',
                    op_distribution:'',
                    investment_tags:'',
                    date_placed:'',
                    contribution_method:'',
                    investment_status:'',
                    investment_in_progress:'',
                    canceled_on:'',
                    inactive_since:'',
                    primary_sponsor:'',
                    primary_company_member:'',

                }, 
                investorForm:{
                    _token : csrf,
                    investor_fname:'',
                    investor_lname:'',
                    investor_email:'',
                    investor_phone_number:'',
                    investor_note:'',
                    investor_tags:'',
                },
                profileForm :{
                    _token : csrf,
                    profile_type:'',
                    profile_fname:'',
                    profile_mname:'',
                    profile_lname:'',
                    profile_ira_name:'',
                    profile_ira_company:'',
                    profile_company_name:'',
                    profile_ira_account_number:'',
                    profile_email:'',
                    profile_fname2:'',
                    profile_mname2:'',
                    profile_lname2:'',
                    profile_email2:'',
                    profile_entity_name:'',
                    profile_number_of_members:'',
                    Profile_distribution:'',
                },